### ISSUE TITLE
ImportError: No module named misc.config

### ISSUE THREAD

**Issue by vijay586** [brangerbriz/docker-StackGAN#7]
When running the demo, encountered with this error.
ran: sudo sh demo/birds_demo.sh 

output:
demo/birds_demo.sh: 10: demo/birds_demo.sh: th: not found
Traceback (most recent call last):
  File "demo/demo.py", line 14, in <module>
    from misc.config import cfg, cfg_from_file

**Comment by jeffersonquispe** [comment]
can you solve this problem?

**Comment by surprisedong** [comment]
I have the same problem.Have you solved it?

**Comment by mohsin127** [comment]
Hey did you solved the error?

**Comment by gowthamvbhat** [comment]
@mohsin127 Creating the folder shortcuts of misc and other in the demo folder solved the issue for me

**Comment by fawnliu** [comment]
You should add a dot in front of the miscc, it works for me.
`from .miscc.config import cfg`
